version: "3.8"

services:
  app:
    build: .
    ports:
      - "5173:5173"
      - "3000:3000"
    environment:
      - MONGO_URI=mongodb://mongo:27017/cupcake-store
      - JWT_SECRET=your_jwt_secret_here
    depends_on:
      - mongo
    volumes:
      - .:/app
      - /app/node_modules

  mongo:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db

volumes:
  mongodb_data:
